version: '3.8'

services:
  # SQL Database for
  # - APScheduler
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi